name             = "perfume-bundle"
client_id        = "e0b1677dced34ca603aac5dd908bd90c"
application_url  = "https://perfume-bundle.vercel.app"
embedded         = true

[access_scopes]
scopes = "read_products,write_products,read_orders,write_cart_transforms"

[auth]
redirect_urls = [
  "https://perfume-bundle.vercel.app/auth/callback",
  "https://perfume-bundle.vercel.app/auth/shopify/callback",
  "https://perfume-bundle.vercel.app/api/auth/callback",
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false